project:
  type: book
  output-dir: docs

book:
  title: "Аккуратное моделирование с помощью R"
  author: "MAX KUHN AND JULIA SILGE"
  date: "2022-12-20"
  sidebar:
    style: docked
    background: light
  page-navigation: true
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - styles.scss
    df-print: paged
    code-fold: true
    cover-image: cover.png
  pdf:
    documentclass: scrreport

editor: visual

